### PR TITLE
added contribution link

### LINKED ISSUE #7: feat:  add contribution url & text to the footer
- We need to add a `contribute here` link to the footer 
- https://github.com/priyankarpal/Portfolio

### PR DESCRIPTION
**Pull request by jayk-gupta**
closes #7 
# screenshot 
cc

### CODE REVIEW

**Review by priyankarpal — CHANGES_REQUESTED** [review]
for the mobile view disable the `contribute here` text & show only the icon.

image

**Comment by jayk-gupta** [comment]
okay!!

**Comment by jayk-gupta** [comment]
Done!
pri-mb

**Review by priyankarpal — APPROVED** [review]
Looks Good 🎉

**Pull request merged**
